name: Deploy docker images

inputs:
  tags:
    required: true
    type: string
  registry:
    required: false
    type: string
    default: ghcr.io
  image_name:
    required: false
    type: string
    default: ${{ github.repository }}
    
outputs:
  slim-images:
    value: ${{ steps.slimTags.outputs.replaced }}
  normal-images:
    value: ${{ steps.normalTags.outputs.replaced }}

runs:
  using: "composite"
  steps:
    
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract slim tags
      uses: frabert/replace-string-action@v2.0
      with:
        pattern: '([\w\d.-]+)'
        string: '${{ inputs.tags }}'
        replace-with: '${{ inputs.registry }}/${{ inputs.image_name }}:$1-slim'
        flags: 'g'
      id: slimTags

    - name: Extract normal tags
      uses: frabert/replace-string-action@v2.0
      with:
        pattern: '([\w\d.-]+)'
        string: '${{ inputs.tags }}'
        replace-with: '${{ inputs.registry }}/${{ inputs.image_name }}:$1'
        flags: 'g'
      id: normalTags

    - name: Deploy slim version
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        target: slim
        tags: ${{ steps.slimTags.outputs.replaced }}
        
    - name: Deploy normal version
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: ${{ steps.normalTags.outputs.replaced }}
