name: master
on:
  push:
    branches: [ master ]


jobs:
  master:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Deploy dev images
      uses: ./.github/actions/deploy_images
      with:
        tag: dev-latest
