name: pull requests checks

on:
  pull_request:
    branches: [ master ]

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:

      - name:  Checkout repo
        uses: actions/checkout@v2

      - name: Validate Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          hadolint_ignore: DL3002 DL3022
          fail_on_error: true


      - name: Validate shell scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          exclude: |
            config/.p10k.zsh
          fail_on_error: true
        
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
