name: release deploy

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  release-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get tag info
        run: |
          TAG=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/})
          SUBJECT=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(subject)')
          BODY=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(body)')
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=subject::$SUBJECT"
          echo "::set-output name=body::$BODY"
        id: getTag

      - name: Deploy images
        uses: ./.github/actions/deploy_images
        with:
          tags: ${{ steps.getTag.outputs.tag }},latest

      - name: Replace release tag in run script
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "latest"
          replace: "${{ steps.getTag.outputs.tag }}"
          include: run.*
          regex: false

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.getTag.outputs.body }}
          files: |
            run.sh
            run.bat
